import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import Header from './layout/header';

const cabinet = localFont({
  src: '../fonts/CabinetGrotesk-Variable.woff2',
  display: 'swap',
  variable: '--font-cabinet',
  adjustFontFallback: 'Times New Roman',
  style: 'normal',
});

const satoshi = localFont({
  src: '../fonts/Satoshi-Variable.woff2',
  display: 'swap',
  variable: '--font-satoshi',
  adjustFontFallback: 'Arial',
  style: 'normal',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${satoshi.variable} ${cabinet.variable} p-0 m-0 antialiased font-sans text-foreground bg-background bg-linear-180 transition-all duration-700 ease-linear`}
      >
        <Header />
        {children}
      </body>
    </html>
  );
}
